# Generated by Django 4.1.7 on 2023-02-22 09:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Course One', 'Course One'), ('Course Two', 'Course Two'), ('Course Three', 'Course Three'), ('Course Four', 'Course Four')], default='Course One', max_length=50)),
                ('day', models.DateField(default=datetime.datetime.now)),
                ('time', models.CharField(choices=[('08h00', '08h00'), ('09h00', '09h00'), ('10h00', '10h00'), ('11h00', '11h00'), ('13h00', '13h00'), ('14h00', '14h00'), ('15h00', '15h00'), ('16h00', '16h00'), ('17h00', '17h00')], default='08h00', max_length=10)),
                ('time_ordered', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
