# Generated by Django 4.1.7 on 2023-02-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Cours Un', 'Cours Un'), ('Cours Deux', 'Cours Deux'), ('Cours Trois', 'Cours Trois'), ('Cours Quatre', 'Cours Quatre')], default='Cours Un', max_length=50),
        ),
    ]
